<?php page_intro('Contato','Vamos falar<br><em>da sua marca?</em>','Conte o contexto. A gente começa pelo problema, não por um pacote pronto.'); ?>
<div class="wrap contact-layout"><aside class="contact-aside"><p class="eyebrow">A conversa começa aqui</p><a href="tel:<?= e(institutional('phone_link')) ?>"><?= e(institutional('phone')) ?></a><a href="mailto:<?= e(institutional('email')) ?>"><?= e(institutional('email')) ?></a><p><?= e(institutional('address')) ?><br><?= e(institutional('city')) ?></p></aside>
<form class="contact-form" action="<?= e(link_url('/api/contact')) ?>" method="post" novalidate>

<input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><div class="honeypot" aria-hidden="true"><label for="website">Deixe em branco</label><input type="text" name="website" id="website" tabindex="-1" autocomplete="off"></div>
<div class="field"><label for="need">O que você precisa?</label><select id="need" name="need"><?php foreach(['Comunicação','Campanha','Marca','Conteúdo','Mídia','Digital','Performance','Ainda não sei'] as $need): ?><option><?= $need ?></option><?php endforeach; ?></select><span class="field-error" id="need-error" data-error="need"></span></div>
<div class="field-grid"><?php foreach(['name'=>['Nome','text','name',true], 'company'=>['Empresa (opcional)','text','organization',false], 'email'=>['E-mail','email','email',true], 'phone'=>['Telefone / WhatsApp (opcional)','tel','tel',false]] as $name=>[$label,$type,$autocomplete,$required]): ?><div class="field"><label for="<?= $name ?>"><?= $label ?></label><input id="<?= $name ?>" name="<?= $name ?>" type="<?= $type ?>" autocomplete="<?= $autocomplete ?>" maxlength="<?= $name==='email'?254:120 ?>" <?= $required?'required':'' ?> aria-describedby="<?= $name ?>-error"><span class="field-error" id="<?= $name ?>-error" data-error="<?= $name ?>"></span></div><?php endforeach; ?></div>
<div class="field"><label for="message">O que a comunicação precisa resolver?</label><textarea id="message" name="message" rows="4" required maxlength="5000" aria-describedby="message-error"></textarea><span class="field-error" id="message-error" data-error="message"></span></div>
<p class="form-legal">Usaremos estes dados para responder à sua solicitação. <a href="<?= e(link_url('/politica-de-privacidade')) ?>">Entenda nossa política de privacidade.</a></p>
<button class="button" type="submit">ENVIAR MENSAGEM <?= arrow() ?></button><progress class="form-progress" aria-label="Enviando mensagem" hidden></progress><div class="form-status" role="status" aria-live="polite" tabindex="-1"></div>
</form></div>
